### ISSUE TITLE
New `finishes` attribute

### ISSUE THREAD

**Issue by kalinon** [crookedneighbor/scryfall-client#29]
Per the update below:
https://scryfall.com/blog/upcoming-api-changes-for-etched-foils-and-glossy-cards-223

- API Card objects now have a finishes attribute, which details if a card is available in nonfoil, foil, etched, or glossy
- The foil and nonfoil top level properties on API card objects are now deprecated

**Comment by crookedneighbor** [comment]
Thanks for the notice. Would you like to open a PR? If not, I’ll get to it soon.

**Comment by crookedneighbor** [comment]
This is out in v0.19.0

**Comment by kalinon** [comment]
Awesome! Thanks!
