### ISSUE TITLE
Following Delay Guidelines

### ISSUE THREAD

**Issue by johnpyp** [crookedneighbor/scryfall-client#3]
On the Scryfall API page it lists that there should be 50-100ms before the next call to the API from 1 IP.

Is this kind of functionality/limiting implemented and enforced naively or should it be implemented separately?

**Comment by crookedneighbor** [comment]
Currently it should be implemented separately, but I'd love to include it as part of the module if you want to open a PR.

**Comment by crookedneighbor** [comment]
This was added in v0.4.0 and can be configured with the [`delayBetweenRequests` option](https://github.com/crookedneighbor/scryfall-client#delaybetweenrequests)

**Comment by crookedneighbor** [comment]
Forgot to mention this early, but if you're still using this library, would love to see the project you're building with it! (Note, that a fix just went out in v0.8.2 to address a change that Scryfall made to their API, so if you haven't updated, do so now)
