### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by ruler501** [crookedneighbor/scryfall-client#41]
I see that the package is MIT licensed in the package.json but would appreciate a LICENSE file as well just so it gets picked up by github and is very clear for usage.

I'm currently evaluating using this as the base for the cards in CubeArtisan (https://github.com/CubeArtisan/cubeartisan) which I'm working to rewrite with a focus on maintainability, testing, reliability, and ease of development.
I'll likely need to modify it some (might not use the Scryfall card format directly ,but also need to consider how each instance of the server gets its database of card/ruling/etc information since I don't want to do a bulk download each time). I'll be glad to upstream any of the features developed that you think will be useful in the base library.

**Comment by crookedneighbor** [comment]
👋 good call out on the missing license file. I’ll try to add it in later tonight. 

Feel free to open up an issue with any features you’d like to include, and we can talk about if it’s in scope for the package.
